apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: loki
  replicas: 1
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:1.4.1
        args:
          - "-config.file=/etc/loki/config.yaml"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 1Gi
        ports:
        - containerPort: 3100
        volumeMounts:
        - name: loki-config
          mountPath: /etc/loki
          readOnly: true
        - name: loki-storage
          mountPath: /data/loki
      volumes:
      - name: loki-config
        configMap:
          name: loki-server-conf
      - name: loki-storage
        hostPath:
          path: /data/loki
          type: DirectoryOrCreate
