apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-node-exporter
  namespace: monitoring
  labels:
    app: prometheus-node-exporter
spec:
  selector:
    matchLabels:
      app: prometheus-node-exporter
  template:
    metadata:
      labels:
        app: prometheus-node-exporter
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      containers:
      - name: node-exporter
        image: prom/node-exporter:v1.0.0-rc.0
        args:
        - --path.rootfs=/host
        - --collector.disable-defaults
        - --collector.cpu
        - --collector.meminfo
        - --collector.filesystem
        - --collector.filesystem.ignored-fs-types=(autofs|binfmt_misc|bpf|cgroup|cgroup2|configfs|debugfs|devpts|devtmpfs|efivarfs|fusectl|hugetlbfs|mqueue|nsfs|overlay|proc|pstore|securityfs|sysfs|tmpfs|tracefs|vfat)
        - --collector.filesystem.ignored-mount-points=/(boot|etc|var)
        ports:
        - containerPort: 9100
        volumeMounts:
        - name: host
          mountPath: /host
          readOnly:  true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: host
        hostPath:
          path: /
