apiVersion: v1
kind: Service
metadata:
  name: prometheus-node-exporter
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: prometheus-node-exporter
  ports:
    - port: 9100
      targetPort: 9100
