apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
      - name: borgman
        rules:
          - alert: Failing
            expr: time() - borgman_last_completed_epoch_seconds{success="1"} > 60*60*24*2
            for: 1m
            labels:
              severity: page
            annotations:
              summary: Borgman has not succeeded in the last 2 days
      - name: pecker
        rules:
          - alert: Failing
            expr: time() - pecker_last_completed_epoch_seconds{success="1"} > 60*60*24*8
            for: 1m
            labels:
              severity: page
            annotations:
              summary: Pecker has not succeeded in the last 8 days
      - name: ddns
        rules:
          - alert: Failing
            expr: time() - ddns_last_completed_epoch_seconds{status="202"} > 60*60
            for: 1m
            labels:
              severity: page
            annotations:
              summary: ddns has not succeeded in the last hour
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    scrape_configs:
      - job_name: 'pushgateway'
        honor_labels: true
        static_configs:
          - targets: ['localhost:9091']
      - job_name: 'labelscrape'
        relabel_configs: # only scrape services with prometheus.io/scrape: "true" annotations
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - monitoring
          - role: service
            namespaces:
              names:
                - sheetheus
    alerting:
      alertmanagers:
        - static_configs:
          - targets:
            - localhost:9093
