apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
      - name: test
        rules:
          - alert: TestAlert
            expr: vector(0)
            for: 1m
            labels:
              alertname: somealert
              severity: page
            annotations:
              summary: Some summary here
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    scrape_configs:
      - job_name: 'pihole'
        static_configs:
          - targets: ['metrics.pihole:9617']
      - job_name: 'pushgateway'
        honor_labels: true
        static_configs:
          - targets: ['localhost:9091']
    alerting:
      alertmanagers:
        - static_configs:
          - targets:
            - localhost:9093
