---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-dns-conf
  labels:
    name: local-dns-conf
  namespace: pihole
data:
  lan.list: |-
    192.168.0.104    troy.test    troy
    192.168.0.107    dns.test     orangepipcplus
    192.168.0.111    bedroom.test orangepizero
    192.168.0.116    ingress.test ingress
    192.168.0.119    bike.test    bike
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsmasq-conf
  labels:
    name: dnsmasq-conf
  namespace: pihole
data:
  02-lan.conf: |-
    addn-hosts=/etc/pihole-local/lan.list
