apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      hostNetwork: true
      containers:
      - name: pihole
        image: pihole/pihole:v5.0
        ports:
        - containerPort: 80
          hostPort: 80
          protocol: TCP
        - containerPort: 53
          hostPort: 53
          protocol: TCP
        - containerPort: 53
          hostPort: 53
          protocol: UDP
        env:
        - name: TZ
          value: America/Los_Angeles
        - name: WEBPASSWORD
          value: password
        - name: DNS1
          value: 1.1.1.1
        - name: DNS2
          value: 8.8.8.8
        - name: ServerIP
          valueFrom:
            fieldRef:
               fieldPath: status.hostIP
        volumeMounts:
        - name: etc-pihole
          mountPath: /etc/pihole/
        - name: dnsmasq
          mountPath: /etc/dnsmasq.d/
        - name: local-dns-conf
          mountPath: /etc/pihole-local
        - name: dnsmasq-conf
          mountPath: /etc/dnsmasq.d/02-lan.conf
          subPath: 02-lan.conf
        readinessProbe:
          exec:
            command: ['dig', '@127.0.0.1', 'google.com']
          timeoutSeconds: 1
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 30
      - name: metrics-exporter
        image: ekofr/pihole-exporter:0.0.9
        ports:
        - containerPort: 9617
        readinessProbe:
          tcpSocket:
            port: 9617
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 9617
          initialDelaySeconds: 15
          periodSeconds: 30
        env:
        - name: PORT
          value: "9617"
        - name: PIHOLE_HOSTNAME
          valueFrom:
            fieldRef:
               fieldPath: status.hostIP
        - name: PIHOLE_PASSWORD
          value: password
        - name: INTERVAL
          value: 1m
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 127.0.0.1
          - 1.1.1.1
      volumes:
      - name: etc-pihole
        emptyDir: {}
      - name: dnsmasq
        emptyDir: {}
      - name: local-dns-conf
        configMap:
          name: local-dns-conf
      - name: dnsmasq-conf
        configMap:
          name: dnsmasq-conf
