---
apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: pihole
spec:
  selector:
    app: pihole
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: dnstcp
      protocol: TCP
      port: 53
    - name: dnsudp
      protocol: UDP
      port: 53
    - name: https
      protocol: TCP
      port: 443
---
apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: pihole
spec:
  selector:
    app: pihole
  type: NodePort
  ports:
    - name: metrics
      protocol: TCP
      port: 9617
