apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: pihole
spec:
  selector:
    app: pihole
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 30080
    - name: dns-tcp
      protocol: TCP
      port: 53
      nodePort: 30053
    - name: dns-udp
      protocol: UDP
      port: 53
      nodePort: 30053
    - name: https
      protocol: TCP
      port: 443
      nodePort: 30443
