kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:v2.2
        name: traefik
        args:
        - --api.insecure=true
        - --providers.file.filename=/etc/traefik/middlewares.toml
        - --providers.kubernetesingress=true
        - --entrypoints.web.address=:80
        - --entrypoints.web.http.middlewares=https-redirect@file,auth@file
        - --entrypoints.websecure.address=:443
        - --entrypoints.websecure.http.middlewares=https-redirect@file,auth@file
        - --entrypoints.websecure.http.tls.certresolver=myhttpchallenge
        - --certificatesresolvers.myhttpchallenge.acme.httpchallenge=true
        - --certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web
        - --certificatesresolvers.myhttpchallenge.acme.email=jchorlton+traefikcerts@gmail.com
        - --certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: admin
          containerPort: 8080
        volumeMounts:
        - name: letsencrypt-storage
          mountPath: /letsencrypt
        - name: traefik-conf
          mountPath: /etc/traefik
      - image: thomseddon/traefik-forward-auth:2
        name: forward-auth
        ports:
        - name: http
          containerPort: 4181
        env:
        - name: COOKIE_DOMAIN
          value: choo.dev
        - name: DOMAIN
          value: joshchorlton.com
        - name: AUTH_HOST
          value: auth.choo.dev
        - name: PROVIDERS_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: ingress
              key: google_client_id
        - name: PROVIDERS_GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: ingress
              key: google_client_secret
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: ingress
              key: forward_auth_secret
      volumes:
      - name: traefik-conf
        configMap:
          name: traefik-conf
      - name: letsencrypt-storage
        hostPath:
          path: /data/letsencrypt
          type: DirectoryOrCreate
