apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-server-conf
  labels:
    name: grafana-server-conf
  namespace: monitoring
data:
  grafana.ini: |-
    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Admin
