apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:6.7.2
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
          - name: grafana-datasources-volume
            mountPath: /etc/grafana/provisioning/datasources/
        ports:
        - containerPort: 3000
      volumes:
        - name: grafana-datasources-volume
          configMap:
            name: grafana-datasources-conf
