{
 "title": "Finances",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Spending Categorized",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "(sum by (category) (max by (account, category, date, name) (transaction_amount_cents{category!=\"Savings\"})) > 0) / 100",
     "legendFormat": "{{category}}"
    },
    {
     "expr": "sum (max by (account, category, date, name) (transaction_amount_cents{category!=\"Savings\"}) > 0) / 100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Top Expenses",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(topk (5, (max by (account, category, date, name) (transaction_amount_cents{category!=\"Savings\"}) > 0)) / 100)"
    }
   ]
  },
  {
   "title": "Savings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum (transaction_amount_cents{category=\"Savings\"}) / 100",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}