{
 "title": "Infra",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "System Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mem Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(1 - ((avg_over_time(node_memory_MemFree_bytes[10m]) + avg_over_time(node_memory_Cached_bytes[10m]) + avg_over_time(node_memory_Buffers_bytes[10m])) / avg_over_time(node_memory_MemTotal_bytes[10m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes / on(instance, device) node_filesystem_size_bytes)",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  { "title": "Backups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - borgman_last_completed_epoch_seconds{success=\"1\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 10 },
   "format": "dateTimeFromNow",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(borgman_last_completed_epoch_seconds)*1000"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(1, borgman_last_completed_epoch_seconds)"
    }
   ]
  },
  { "title": "Dynamic DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - ddns_last_completed_epoch_seconds{status=\"202\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 19 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(ddns_last_completed_epoch_seconds)*1000"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ddns_last_completed_epoch_seconds"
    }
   ]
  }
 ]
}