apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheetheus
  namespace: sheetheus
spec:
  selector:
    matchLabels:
      app: sheetheus
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: sheetheus
    spec:
      containers:
      - name: sheetheus
        image: jchorl/sheetheus:sha-12dd1bf
        env:
        - name: PORT
          value: "8080"
        - name: FINANCE_SPREADSHEET_ID
          value: "1yiHbSLDIIYPZPJrgfSnpJZKelaQ3CFVE9bFPs77MMAI"
        - name: RO_FILESYSTEM
          value: "1"
        volumeMounts:
          - name: creds
            mountPath: /opt/app/.creds
            readOnly: true
        ports:
        - containerPort: 8080
      volumes:
      - name: creds
        secret:
          secretName: sheetheus
