apiVersion: v1
kind: Service
metadata:
  name: sheetheus
  namespace: sheetheus
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: sheetheus
  ports:
    - port: 8080
      targetPort: 8080
